name: CI

on:
  push:
    branches: [ next ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn install

      - name: Export the site
        run: |
          yarn next build
          yarn next export
          
      - name: Push it to master
        run: |
          git config user.name "Álex González"
          git config user.email "agonzalezro@gmail.com"
          find . -maxdepth 1 -not -name "out" -not -name ".git" -not -name "." -not -name ".." | xargs rm -rf
          mv out/* .
          rm -rf out
          touch .nojekyll
          git add .
          git commit -m "Automagically deployed"
          git push -f origin HEAD:master